Update lmsbookworm

diff --git a/Android/lmsbookworm b/Android/lmsbookworm
--- a/Android/lmsbookworm
+++ b/Android/lmsbookworm
@@ -39,7 +39,7 @@ if [  ! -d '/usr/share/squeezeboxserver' ]; then
   rm logitechmediaserver*.deb
   rm servers.json
   wget https://lms-community.github.io/lms-server-repository/servers.json
-  wget \$(jq -r '."8.4.1".deb.url' servers.json)
+  wget \$(jq -r '.latest.deb.url' servers.json)
   apt -y install ./logitechmediaserver*.deb
   touch .lmsfirstinstall
 fi
@@ -100,10 +100,10 @@ rm servers.json
 error=""
 wget https://lms-community.github.io/lms-server-repository/servers.json || error="ERROR: Can't get latest server details"
 if [ -z "\$error" ]; then
-  if [ \$(apt show logitechmediaserver | grep ^Version: | cut -d' ' -f2) == \$(jq -r '."8.4.1".deb.url' servers.json | cut -d'_' -f2) ]; then
+  if [ \$(apt show logitechmediaserver | grep ^Version: | cut -d' ' -f2) == \$(jq -r '.latest.deb.url' servers.json | cut -d'_' -f2) ]; then
     error="You already have the latest version"
   else
-    wget \$(jq -r '."8.4.1".deb.url' servers.json) || error="ERROR: Can't find latest server download"
+    wget \$(jq -r '.latest.deb.url' servers.json) || error="ERROR: Can't find latest server download"
     if [ -z "\$error" ]; then
       apt -y install ./logitechmediaserver*.deb || error="ERROR: installation failed"
       if [ -z "\$error" ] && [ ! -f /usr/share/perl5/Slim/Utils/OS/Custom.pm ]; then
