Update lmstd

diff --git a/Android/lmstd b/Android/lmstd
--- a/Android/lmstd
+++ b/Android/lmstd
@@ -58,11 +58,11 @@ rm servers.json
 error=""
 wget https://lms-community.github.io/lms-server-repository/servers.json || error="ERROR: Can't get latest server details"
 if [ -z "\$error" ]; then
-  wget \$(jq -r '."8.4.1".deb.url' servers.json) || error="ERROR: Can't find latest server download"
-  if [ -z "\$error" ]; then
-    if [ \$(apt show logitechmediaserver | grep ^Version: | cut -d' ' -f2) == \$(ls logitechmediaserver* | cut -d'_' -f2) ]; then
-      error="You already have the latest version"
-    else
+  if [ \$(apt show logitechmediaserver | grep ^Version: | cut -d' ' -f2) == \$(jq -r '."8.4.1".deb.url' servers.json | cut -d'_' -f2) ]; then
+    error="You already have the latest version"
+  else
+    wget \$(jq -r '."8.4.1".deb.url' servers.json) || error="ERROR: Can't find latest server download"
+    if [ -z "\$error" ]; then
       apt -y install ./logitechmediaserver*.deb || error="ERROR: installation failed"
     fi
   fi
