Workaround RHEL4 killproc issues, switch to bundled flac and sox
git-svn-id: file:///home/awy/mirror/slim/trunk/platforms@14555 62299810-d8cb-41fd-93b7-d32162e5a4a4

diff --git a/redhat/squeezecenter.init b/redhat/squeezecenter.init
--- a/redhat/squeezecenter.init
+++ b/redhat/squeezecenter.init
@@ -72,6 +72,13 @@ if [ -f /etc/redhat-release ] ; then
 		fi
 		killproc $KILLPROC_ARGS $SQUEEZECENTER_BIN
 		RETVAL=$?
+                if [ $RETVAL -ne 0 ]; then
+                        # If killproc fails, try killall (fix for RHEL4)
+                        killall squeezecenter-server
+                        RETVAL=$?
+                        [ $RETVAL -eq 0 ] && echo_success
+                        [ $RETVAL -ne 0 ] && echo_failure
+                fi
 		echo
 		[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
 		return $RETVAL
@@ -79,6 +86,7 @@ if [ -f /etc/redhat-release ] ; then
 
 	restart() {
 		stop
+		sleep 2
 		start
 	}
 
